Repository lugenx/ecohabit, pull requests merged in 2022-12, with the labels that each got.

#98 Removed unneeded boilerplate
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/reportWebVitals.js
  client/src/setupTests.js
Labels: front-end

#100 Update README.md
  README.md
Labels: documentation

#82 navbar design
  client/package-lock.json
  client/package.json
  client/src/components/NavBar/NavBar.js
  client/src/components/NavBar/NavBar.module.css
  client/src/components/NavBar/recycling.svg
Labels: front-end

#99 db and models setup
  server/.env.example
  server/index.js
  server/src/controller/answerController.js
  server/src/controller/earth911controller.js
  server/src/controller/habitController.js
  server/src/controller/userController.js
  server/src/models/answerModel.js
  server/src/models/habitModel.js
  server/src/models/userModel.js
  server/src/routes/answerRoutes.js
  server/src/routes/habitRoutes.js
  server/src/routes/userRoutes.js
Labels: back-end
